"""empty message

Revision ID: 6c4263d85c91
Revises: 2cf4fbaf518b
Create Date: 2021-04-07 11:52:19.241497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4263d85c91'
down_revision = '2cf4fbaf518b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('image', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_blog_image'), 'blog', ['image'], unique=False)
    op.add_column('project', sa.Column('image', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_project_image'), 'project', ['image'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_image'), table_name='project')
    op.drop_column('project', 'image')
    op.drop_index(op.f('ix_blog_image'), table_name='blog')
    op.drop_column('blog', 'image')
    # ### end Alembic commands ###
