"""empty message

Revision ID: 8111656fac42
Revises: 1cdb733e33ad
Create Date: 2021-04-04 15:59:17.834155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8111656fac42'
down_revision = '1cdb733e33ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('cat', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_cat'), 'blog', ['cat'], unique=True)
    op.create_index(op.f('ix_blog_content'), 'blog', ['content'], unique=True)
    op.create_index(op.f('ix_blog_description'), 'blog', ['description'], unique=True)
    op.create_index(op.f('ix_blog_title'), 'blog', ['title'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('cat', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_cat'), 'project', ['cat'], unique=True)
    op.create_index(op.f('ix_project_content'), 'project', ['content'], unique=True)
    op.create_index(op.f('ix_project_description'), 'project', ['description'], unique=True)
    op.create_index(op.f('ix_project_title'), 'project', ['title'], unique=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.drop_index(op.f('ix_project_title'), table_name='project')
    op.drop_index(op.f('ix_project_description'), table_name='project')
    op.drop_index(op.f('ix_project_content'), table_name='project')
    op.drop_index(op.f('ix_project_cat'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_blog_title'), table_name='blog')
    op.drop_index(op.f('ix_blog_description'), table_name='blog')
    op.drop_index(op.f('ix_blog_content'), table_name='blog')
    op.drop_index(op.f('ix_blog_cat'), table_name='blog')
    op.drop_table('blog')
    # ### end Alembic commands ###
